# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.Customer')),
            ],
        ),
    ]
