# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_orderslist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOrderHelper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_packages', models.IntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.OrdersList')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Orders.Products')),
            ],
        ),
    ]
