# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0005_temporder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temporder',
            old_name='mnumber_of_packs',
            new_name='number_of_packs',
        ),
    ]
