# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 08:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0006_auto_20170513_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorderhelper',
            name='changes',
            field=models.CharField(default=datetime.datetime(2017, 6, 2, 11, 51, 44, 585590), max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productorderhelper',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
