# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0007_auto_20170602_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListAllOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.OrdersList')),
            ],
        ),
        migrations.CreateModel(
            name='ListOrdersDone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.OrdersList')),
            ],
        ),
        migrations.CreateModel(
            name='ListOrdersHereToTake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.OrdersList')),
            ],
        ),
        migrations.CreateModel(
            name='ListOrdersReadyToCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.OrdersList')),
            ],
        ),
        migrations.CreateModel(
            name='ListOrdersReadyToPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.OrdersList')),
            ],
        ),
    ]
