# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-01 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0009_auto_20170701_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListOrdersToConfirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.OrdersList')),
            ],
        ),
    ]
