# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-19 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0012_orderslist_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_packages', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('p', 'prepared'), ('to', 'taken_orders'), ('tno', 'taken_not_orders')], max_length=15)),
                ('owner', models.CharField(max_length=15)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Orders.Products')),
            ],
        ),
    ]
