# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-25 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0013_productcounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsSummer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('sum_ordered', models.IntegerField()),
                ('sum_prepared', models.IntegerField()),
                ('sum_taken', models.IntegerField()),
                ('sum_still_needed_for_orders', models.IntegerField()),
                ('sum_available', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Orders.Products')),
            ],
        ),
    ]
