# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-09 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0014_productssummer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcounter',
            name='action',
            field=models.CharField(choices=[('p', 'prepared'), ('to', 'taken_orders'), ('tno', 'taken_not_orders'), ('ro', 'returned_orders')], max_length=15),
        ),
    ]
