# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0016_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listallorders',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='listordersconfirmed',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='listordersdone',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='listordersheretotake',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='listordersreadytocheck',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='listordersreadytopay',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='listorderstoconfirm',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='note',
            name='order_id',
        ),
        migrations.AddField(
            model_name='orderslist',
            name='foreign_order_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='foreign_product_id',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ListAllOrders',
        ),
        migrations.DeleteModel(
            name='ListOrdersConfirmed',
        ),
        migrations.DeleteModel(
            name='ListOrdersDone',
        ),
        migrations.DeleteModel(
            name='ListOrdersHereToTake',
        ),
        migrations.DeleteModel(
            name='ListOrdersReadyToCheck',
        ),
        migrations.DeleteModel(
            name='ListOrdersReadyToPay',
        ),
        migrations.DeleteModel(
            name='ListOrdersToConfirm',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
