# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-17 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0017_auto_20180303_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderslist',
            name='delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderslist',
            name='for_second_holiday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderslist',
            name='take_on_friday',
            field=models.BooleanField(default=False),
        ),
    ]
