# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0018_auto_20180317_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='productssummer',
            name='sum_extras',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productssummer',
            name='sum_still_need_to_prepare',
            field=models.IntegerField(default=0),
        ),
    ]
