# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-31 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0019_auto_20180327_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='foreign_product_id_2',
            field=models.IntegerField(default=0),
        ),
    ]
